import { services as fallbackServices } from './src/data/services.js';
import { formatServicePrice } from './src/utils/currency.js';
import { initRequestFlow } from './src/ui/request-flow.js';
import { initRequestTracking } from './src/ui/request-tracking.js';
import { initServiceSearch } from './src/ui/service-search.js';
import { initCustomerArea } from './src/ui/customer-area.js';
import { initPWAInstall } from './src/ui/pwa-install.js';
import { initHowItWorks } from './how-it-works.js';
import { loadCatalog, createRequest, myRequests, subscribeUser } from './src/services/api.js';
import { currentUser } from './src/services/supabase.js';
import { initAuthUI } from './src/services/auth-ui.js';

const icons={maintenance:'ri-tools-line',painting:'ri-paint-brush-line',plumbing:'ri-drop-line',electrical:'ri-flashlight-line',cleaning:'ri-sparkling-line',automotive:'ri-car-line',assembly:'ri-hammer-line',gardening:'ri-plant-line','air-conditioning':'ri-temp-cold-line',appliances:'ri-home-gear-line',technology:'ri-computer-line',security:'ri-shield-keyhole-line',events:'ri-camera-line',moving:'ri-truck-line'};
const categoryNames={maintenance:'Reparos',painting:'Pintura',plumbing:'Hidráulica',electrical:'Elétrica',cleaning:'Limpeza',automotive:'Automotivo',assembly:'Montagem',gardening:'Jardinagem','air-conditioning':'Climatização',appliances:'Eletrodomésticos',technology:'Tecnologia',security:'Segurança',events:'Eventos',moving:'Fretes'};
const priceCopy={fixed:['Preço definido','Valor base definido para este serviço.'],starting_at:['A partir de','O valor pode variar conforme os detalhes do atendimento.'],hourly:['Por hora','O total depende do tempo necessário para execução.'],per_square_meter:['Por área','O total depende da metragem do serviço.'],quote:['Sob orçamento','Envie os detalhes para receber uma avaliação mais precisa.'],technical_visit:['Avaliação técnica','Pode ser necessário avaliar o local ou equipamento antes do orçamento.']};
let services=fallbackServices,activeCategory='all',selectedService=null,unsubscribeUser=null;
const grid=document.querySelector('#services-grid'),emptyState=document.querySelector('#empty-state'),searchInput=document.querySelector('#service-search'),clearSearch=document.querySelector('#clear-search'),resultCount=document.querySelector('#services-result-count'),chips=[...document.querySelectorAll('.category-chip')],modal=document.querySelector('#service-modal');
function normalized(v=''){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function showToast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),3200)}
function renderServices(){const q=normalized(searchInput?.value||'');const list=services.filter(s=>s.active!==false&&(activeCategory==='all'||s.category===activeCategory)&&(!q||normalized(s.name+' '+s.description).includes(q)));grid.innerHTML=list.map(s=>`<article class="service-card" tabindex="0" data-service-id="${s.id}"><div class="service-card__icon"><i class="${icons[s.category]||'ri-tools-line'}"></i></div><span>${categoryNames[s.category]||s.category}</span><h3>${s.name}</h3><p>${s.description}</p><div class="service-card__bottom"><strong>${formatServicePrice(s)}</strong><i class="ri-arrow-right-line"></i></div></article>`).join('');emptyState.hidden=!!list.length;resultCount.textContent=`${list.length} serviço${list.length===1?'':'s'} disponível${list.length===1?'':'s'}`}
function openService(s){selectedService=s;const pc=priceCopy[s.priceType]||priceCopy.quote;document.querySelector('#modal-icon').innerHTML=`<i class="${icons[s.category]||'ri-tools-line'}"></i>`;document.querySelector('#modal-category').textContent=categoryNames[s.category]||s.category;document.querySelector('#modal-title').textContent=s.name;document.querySelector('#modal-description').textContent=s.description;document.querySelector('#modal-price-label').textContent=pc[0];document.querySelector('#modal-price').textContent=formatServicePrice(s);document.querySelector('#modal-price-help').textContent=pc[1];document.querySelector('#modal-service-steps').innerHTML='<div><i class="ri-file-text-line"></i><span><strong>Descreva</strong><small>Conte o que precisa.</small></span></div><div><i class="ri-map-pin-line"></i><span><strong>Informe o local</strong><small>Onde será o atendimento.</small></span></div><div><i class="ri-calendar-line"></i><span><strong>Escolha quando</strong><small>Indique sua preferência.</small></span></div>';modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.modal__close').focus()}
function closeModal(){modal.hidden=true;document.body.style.overflow='';selectedService=null}
const requestTracking=initRequestTracking();
const requestFlow=initRequestFlow({onComplete:data=>{requestTracking.open(data);renderSavedRequestAction()}});
const authUI=initAuthUI({toast:showToast,onChange:refreshAuth});
async function refreshAuth(){const user=await currentUser();document.documentElement.classList.toggle('is-authenticated',!!user);if(unsubscribeUser){unsubscribeUser();unsubscribeUser=null}if(user){unsubscribeUser=await subscribeUser(()=>{showToast('Você recebeu uma atualização.');customerArea.render?.()})}}
async function submitBackendRequest(payload){const user=await currentUser();if(!user){return new Promise((resolve,reject)=>authUI.open({onSuccess:async()=>{try{resolve(await createRequest(payload))}catch(e){reject(e)}},onCancel:()=>reject(new Error('LOGIN_REQUIRED'))}))}return createRequest(payload)}
window.StateServices={auth:authUI,currentUser,myRequests,createRequest:submitBackendRequest};
function renderSavedRequestAction(){let b=document.querySelector('#saved-request-action');if(!requestTracking.hasSaved()){b?.remove();return}if(!b){b=document.createElement('button');b.id='saved-request-action';b.className='saved-request-action';b.type='button';b.innerHTML='<i class="ri-route-line"></i><span><small>Solicitação em andamento</small><strong>Acompanhar minha solicitação</strong></span><i class="ri-arrow-right-s-line"></i>';document.body.appendChild(b);b.addEventListener('click',()=>requestTracking.openSaved())}}
grid.addEventListener('click',e=>{const c=e.target.closest('[data-service-id]');if(c){const s=services.find(x=>x.id===c.dataset.serviceId);if(s)openService(s)}});
grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-service-id]')){e.preventDefault();const s=services.find(x=>x.id===e.target.dataset.serviceId);if(s)openService(s)}});
chips.forEach(c=>c.addEventListener('click',()=>{activeCategory=c.dataset.category;chips.forEach(x=>x.classList.toggle('active',x===c));renderServices()}));
searchInput?.addEventListener('input',renderServices);clearSearch?.addEventListener('click',()=>{searchInput.value='';searchInput.focus();renderServices()});
initServiceSearch({input:searchInput,clearButton:clearSearch,grid,emptyState,resultCount});initHowItWorks();const customerArea=initCustomerArea({tracking:requestTracking});const pwaInstall=initPWAInstall({toast:showToast});
document.querySelectorAll('[data-open-customer]').forEach(b=>b.addEventListener('click',async e=>{if(!(await currentUser())){e.preventDefault();e.stopImmediatePropagation();authUI.open()}}));
const topbar=document.querySelector('.topbar'),headerAction=document.querySelector('.header-action'),searchBox=document.querySelector('.search-box'),searchHome=searchBox?.parentNode,searchAnchor=searchBox?.nextSibling;
function closeHeaderSearch(){if(!topbar?.classList.contains('search-open'))return;topbar.classList.remove('search-open');headerAction?.querySelector('i')?.classList.replace('ri-close-line','ri-search-line');if(searchHome&&searchBox)searchHome.insertBefore(searchBox,searchAnchor)}
headerAction?.addEventListener('click',e=>{e.preventDefault();if(innerWidth>600){document.querySelector('#services')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>searchInput?.focus({preventScroll:true}),450);return}if(topbar.classList.contains('search-open')){closeHeaderSearch();searchInput?.blur();return}topbar.classList.add('search-open');topbar.insertBefore(searchBox,headerAction);headerAction.querySelector('i')?.classList.replace('ri-search-line','ri-close-line');setTimeout(()=>searchInput?.focus({preventScroll:true}),80)});
addEventListener('resize',()=>{if(innerWidth>600)closeHeaderSearch()});modal.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!modal.hidden)closeModal();closeHeaderSearch()}});
document.querySelector('#request-service').addEventListener('click',()=>{const s=selectedService;closeModal();requestFlow.open(s)});
document.querySelector('#custom-request').addEventListener('click',()=>{showToast('Escolha um serviço para criar uma solicitação.')});
document.querySelector('#year').textContent=new Date().getFullYear();
const sections=[...document.querySelectorAll('section[id]')],navLinks=[...document.querySelectorAll('.bottom-nav a:not([data-open-customer])')];function updateNavigation(){let current='home';sections.forEach(s=>{if(window.scrollY>=s.offsetTop-180)current=s.id});navLinks.forEach(l=>l.classList.toggle('active-link',l.getAttribute('href')===`#${current}`))}window.addEventListener('scroll',updateNavigation,{passive:true});
function hasActiveFlow(){return Boolean(document.querySelector('#request-flow:not([hidden]),.tracking-view:not([hidden]),#customer-area:not([hidden]),#service-modal:not([hidden]),.pwa-install:not([hidden])')||document.activeElement?.matches('input,textarea,select'))}
function setConnectionState(){document.documentElement.classList.toggle('is-offline',!navigator.onLine);if(!navigator.onLine)showToast('Você está offline. O conteúdo disponível continua acessível.')}addEventListener('online',()=>{setConnectionState();showToast('Conexão restabelecida.')});addEventListener('offline',setConnectionState);setConnectionState();
function registerPWA(){if(!('serviceWorker'in navigator))return;let pendingWorker=null,reloadForUpdate=false;const activate=worker=>{if(!worker)return;if(hasActiveFlow()){pendingWorker=worker;showToast('Atualização pronta. Será aplicada quando você terminar.');return}reloadForUpdate=true;worker.postMessage({type:'SKIP_WAITING'})};const tryPending=()=>{if(pendingWorker&&!hasActiveFlow()){const worker=pendingWorker;pendingWorker=null;activate(worker)}};document.addEventListener('click',()=>setTimeout(tryPending,250));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloadForUpdate&&!hasActiveFlow())location.reload()});addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});if(r.waiting)activate(r.waiting);r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){showToast('Nova versão disponível.');activate(w)}})});await r.update()}catch(e){console.warn('PWA service worker unavailable:',e)}},{once:true})}
async function hydrateCatalog(){try{const rows=await loadCatalog();if(rows?.length)services=rows.map(r=>({id:r.id,backendId:r.id,slug:r.slug,category:r.category?.slug,name:r.name,description:r.description||'',priceType:r.metadata?.price_type||'quote',priceCents:r.base_price==null?null:Math.round(Number(r.base_price)*100),active:true}));renderServices()}catch(e){console.warn('Using offline catalog fallback',e)}}
renderServices();renderSavedRequestAction();updateNavigation();registerPWA();refreshAuth();hydrateCatalog();setTimeout(()=>{if(!pwaInstall.isStandalone()&&pwaInstall.canInstall()&&!requestTracking.hasSaved())pwaInstall.open()},12000);
