import {supabase,currentUser} from './supabase.js';
let orgId=null;
export async function getOrganizationId(){if(orgId)return orgId;const {data,error}=await supabase.from('organizations').select('id').eq('slug','state-services').eq('status','active').single();if(error)throw error;orgId=data.id;return orgId}
export async function loadCatalog(){const oid=await getOrganizationId();const {data,error}=await supabase.from('services').select('id,name,slug,description,base_price,metadata,category:service_categories(id,name,slug,icon)').eq('organization_id',oid).eq('is_active',true).order('name');if(error)throw error;return data}
export async function ensureCustomer(){const oid=await getOrganizationId();const {error}=await supabase.rpc('join_as_customer',{p_organization_id:oid});if(error)throw error;return oid}
export async function saveAddress(a){const user=await currentUser();if(!user)throw new Error('LOGIN_REQUIRED');const payload={profile_id:user.id,label:a.label||'Atendimento',street:a.street,number:a.number,complement:a.complement||null,district:a.district,city:a.city||a.district,state_code:(a.stateCode||'SC').toUpperCase(),postal_code:a.zip||null};const {data,error}=await supabase.from('addresses').insert(payload).select().single();if(error)throw error;return data}
export async function createRequest(input){const user=await currentUser();if(!user)throw new Error('LOGIN_REQUIRED');const oid=await ensureCustomer();const address=await saveAddress(input.address);const preferred=input.date?new Date(input.date+'T'+(input.startTime||'12:00')+':00').toISOString():null;const {data,error}=await supabase.from('service_requests').insert({organization_id:oid,customer_id:user.id,service_id:input.serviceId,address_id:address.id,state_code:(input.address?.stateCode||'SC').toUpperCase(),title:input.title,description:input.description,status:'open',preferred_at:preferred,metadata:{period:input.period||null,end_time:input.endTime||null}}).select().single();if(error)throw error;await uploadAttachments(data,input.files||[]);return data}
export async function uploadAttachments(request,files){const user=await currentUser();if(!user||!files.length)return;const oid=request.organization_id;for(const file of files){const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'');const path=`${request.id}/${user.id}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('request-attachments').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const {error:dbError}=await supabase.from('request_attachments').insert({organization_id:oid,request_id:request.id,uploaded_by:user.id,storage_bucket:'request-attachments',storage_path:path,file_name:file.name,mime_type:file.type||null,size_bytes:file.size,attachment_type:'customer'});if(dbError)throw dbError}}
export async function myRequests(){const user=await currentUser();if(!user)return[];const {data,error}=await supabase.from('service_requests').select('*,service:services(name,slug),quotes(*)').eq('customer_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data}
export async function myAddresses(){const user=await currentUser();if(!user)return[];const {data,error}=await supabase.from('addresses').select('*').eq('profile_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data}
export async function myProfile(){const user=await currentUser();if(!user)return null;const {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;return {...data,email:user.email}}
export async function updateProfile(values){const user=await currentUser();if(!user)throw new Error('LOGIN_REQUIRED');const {data,error}=await supabase.from('profiles').update(values).eq('id',user.id).select().single();if(error)throw error;return data}
export async function acceptQuote(id,accept=true){const {data,error}=await supabase.rpc('respond_to_quote',{p_quote_id:id,p_accept:accept});if(error)throw error;return data}
export async function markNotification(id,read=true){const {data,error}=await supabase.rpc('mark_notification_read',{p_notification_id:id,p_read:read});if(error)throw error;return data}
export async function notifications(){const user=await currentUser();if(!user)return[];const {data,error}=await supabase.from('notifications').select('*').eq('profile_id',user.id).order('created_at',{ascending:false}).limit(50);if(error)throw error;return data}
export async function dashboard(){return supabase.rpc('dashboard_summary',{p_organization_id:await getOrganizationId()})}
export async function createReview(requestId,rating,comment=''){const {data,error}=await supabase.rpc('create_review',{p_request_id:requestId,p_rating:rating,p_comment:comment});if(error)throw error;return data}
export async function subscribeUser(onEvent){const user=await currentUser();if(!user)return()=>{};await supabase.realtime.setAuth();const ch=supabase.channel(`user:${user.id}`,{config:{private:true}}).on('broadcast',{event:'INSERT'},onEvent).on('broadcast',{event:'UPDATE'},onEvent).subscribe();return()=>supabase.removeChannel(ch)}
export async function subscribeRequest(id,onEvent){await supabase.realtime.setAuth();const ch=supabase.channel(`request:${id}`,{config:{private:true}}).on('broadcast',{event:'*'},onEvent).subscribe();return()=>supabase.removeChannel(ch)}
